#!/usr/bin/env php
<?php

declare(strict_types=1);//optional

require_once 'vendor/autoload.php'; //if installed via composer

/**
 * This is the doccumentation that will apper when you type help.
 */
class example {
    /**
    * This documentation appears if you use --help with tryMe
    */
    public function tryMe(bool $bool, string $string, float $float, int $int){
        var_dump(func_get_args());
    }
};

(new BHayes\CLI\CLI(new Example()))->run();
